<a href="https://colab.research.google.com/github/imhyunho99/2023-1--MachineLearning/blob/main/02_TrainSetAndTestSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**02 Trainset and Testset**


In [39]:
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8, 
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7, 
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]     

In [40]:
fish_data = [[l, w] for l, w in zip(fish_length, fish_weight)]
fish_target = [0]*35 + [1]*14 #도미 35마리 빙어 14마리

In [41]:
import numpy as np
#https://numpy.org/doc/stable/user/index.html#user

In [42]:
input_arr = np.array(fish_data)
target_arr = np.array(fish_target)
target_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [73]:
#만약 훈련세트를 고루 설정하지 못하면 예측이 정확하지 못하거나, 예측을 하지 못할 수 있다.(샘플링 편향, Sampling bias)
#일단 마구잡이로 섞지만 클래스 별로 골고루 샘플링을 하는것이 예측에 좋다.
np.random.seed(1)#seed번호 42 많이 쓰는데 의미는 없는듯, Seednumber를 하나 주고 다음번에 또 그 seedN을 사용하면 이전의 matrix를 그대로 가져다 준다(testset 고정)
index = np.arange(49)
np.random.shuffle(index)
index

array([27, 34, 39, 48,  2,  3, 42, 29, 45, 30, 31, 38, 21, 35, 19, 41, 36,
       26, 22, 13, 40, 17, 44, 24, 23,  4, 32, 14, 10, 28, 47, 33, 18, 20,
       25,  6,  7, 46,  1, 16,  0, 15,  5, 11,  9,  8, 12, 43, 37])

In [74]:
train_input = input_arr[index[:35]] #0~34번째 인덱스까지는 훈련데이터로 사용
print("train_input:", train_input)
train_target = target_arr[index[:35]]
print("train_target:", train_target)

train_input: [[  36.   714. ]
 [  41.   950. ]
 [  11.2    9.8]
 [  15.    19.9]
 [  26.5  340. ]
 [  29.   363. ]
 [  11.8    9.9]
 [  37.  1000. ]
 [  12.4   13.4]
 [  38.5  920. ]
 [  38.5  955. ]
 [  11.     9.7]
 [  34.   685. ]
 [   9.8    6.7]
 [  33.5  650. ]
 [  11.8   10. ]
 [  10.5    7.5]
 [  35.   720. ]
 [  34.5  620. ]
 [  32.   340. ]
 [  11.3    8.7]
 [  33.   700. ]
 [  12.2   12.2]
 [  35.   700. ]
 [  35.   680. ]
 [  29.   430. ]
 [  39.5  925. ]
 [  32.   600. ]
 [  31.   475. ]
 [  36.   850. ]
 [  14.3   19.7]
 [  41.   975. ]
 [  33.5  610. ]
 [  34.   575. ]
 [  35.   725. ]]
train_target: [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0]


In [76]:
print(train_input.shape)
print(test_input.shape)

(35, 2)
(14, 2)


from numpy.core.fromnumeric import ndim

target_arr.shape 배열의 형태 반환

target_arr.ndim 배열의 차원 반환 

In [54]:
test_input = input_arr[index[35:]]#35번째 인덱스부터는 평가데이터로 사용
test_target = target_arr[index[35:]]

In [55]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()

In [56]:
kn.fit(train_input, train_target)

KNeighborsClassifier()

In [57]:
print("train:", kn.score(train_input, train_target))#훈련 세트에 대한 판단
print("test:", kn.score(test_input, test_target))#성능테스트

train: 1.0
test: 1.0


In [79]:
print(kn.predict(test_input))
print(kn.score(test_input, test_target))

[0 0 1 1 0 1 1 0 1 0 0 1 1 1]
1.0


In [80]:
test_target

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1])